[package]
edition = "2021"
name = "advent-of-code"
version = "0.1.0"

[dependencies]
itertools = "0.10.5"
lazy_static = "1.4.0"
num = "0.4.1"
rayon = "1.8.0"
regex = "1.7.0"
z3 = { version = "0.12.1", features = ["static-link-z3"] }
